<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="table" params="prefix parent *origin">

    <!-- TABLE PROPERTIES -->
    <xacro:property name="table_length" value="2" />
    <xacro:property name="table_width" value="1" />
    <xacro:property name="table_height" value="1" />
    <xacro:property name="table_thickness" value="0.05" />
    <xacro:property name="leg_length" value="${table_height - table_thickness}" />
    <xacro:property name="leg_radius" value="0.05" />

    <!-- Base Joint (places table top frame in world) -->
    <joint name="${prefix}base_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${prefix}top" />
    </joint>

    <!-- Table Top -->
    <link name="${prefix}top">
      <visual>
        <!-- top frame is at surface, so geometry goes downward -->
        <origin xyz="0 0 ${-table_thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${table_length} ${table_width} ${table_thickness}" />
        </geometry>
        <material name="brown"/>
      </visual>
    </link>

    <!-- LEG POSITIONS -->
    <xacro:property name="x_pos" value="${table_length/2 - leg_radius}" />
    <xacro:property name="y_pos" value="${table_width/2 - leg_radius}" />

    <!-- ================= LEGS ================= -->

    <!-- Leg 1 -->
    <joint name="${prefix}leg1_joint" type="fixed">
      <parent link="${prefix}top"/>
      <child link="${prefix}leg1"/>
      <origin xyz="${x_pos} ${y_pos} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}leg1">
      <visual>
        <origin xyz="0 0 ${-leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}" />
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

    <!-- Leg 2 -->
    <joint name="${prefix}leg2_joint" type="fixed">
      <parent link="${prefix}top"/>
      <child link="${prefix}leg2"/>
      <origin xyz="${x_pos} ${-y_pos} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}leg2">
      <visual>
        <origin xyz="0 0 ${-leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}" />
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

    <!-- Leg 3 -->
    <joint name="${prefix}leg3_joint" type="fixed">
      <parent link="${prefix}top"/>
      <child link="${prefix}leg3"/>
      <origin xyz="${-x_pos} ${y_pos} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}leg3">
      <visual>
        <origin xyz="0 0 ${-leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}" />
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

    <!-- Leg 4 -->
    <joint name="${prefix}leg4_joint" type="fixed">
      <parent link="${prefix}top"/>
      <child link="${prefix}leg4"/>
      <origin xyz="${-x_pos} ${-y_pos} 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}leg4">
      <visual>
        <origin xyz="0 0 ${-leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}" />
        </geometry>
        <material name="light_grey"/>
      </visual>
    </link>

  </xacro:macro>

</robot>

